### ISSUE TITLE
one-step approve and auto-merge label?

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dlang-bot#74]
Would save a couple of clicks if we could merge approve and adding the auto-merge label into a single link or so.
https://github.com/dlang/phobos/pull/5382#issuecomment-303782560

**Comment by wilzbach** [comment]
Hmm, sometimes you just want to approve and wait until others object or there's a second approval. So
- approval -> auto-merge doesn't work

Moreover, adding a label "auto-merge-approved" and letting the Dlang-Bot approve the PR seems a bit confusing as well (especially because we currently query GitHub  for the author of the approval to get the "merged-on-behalf-of" commit message).

So imho this is a won't fix - approving and adding the label doesn't that much time compared to the review anyways...

**Comment by MartinNowak** [comment]
Maybe we could exploit some CSRF on github and redirect a single button to perform both ;).

**Comment by MartinNowak** [comment]
Would be better to simplify the workflow than popping up a warning about auto-merge/approval missing.
In fact I'd take auto-merge as an implicit approval, b/c only maintainers can set it.

You could turn it the other way round and take an approval as an OK to auto-merge within 5 minutes, setting the label right away.

**Comment by wilzbach** [comment]
> You could turn it the other way round and take an approval by a maintainer as an OK to auto-merge within 5 minutes, setting the label right away, so that people can remove it if that was unintended.

That would be really annoying, because I often review/approve PRs and when they are complicated I wait for a few days if other reviewers raise concerns.Though of course that could be automated too, but it hasn't been a huge problem so far.

**Comment by CyberShadow** [comment]
@thewilsonator @RazvanN7 Any thoughts?

**Comment by thewilsonator** [comment]
no, i don't think its needed,

**Comment by Geod24** [comment]
I wouldn't mind if the bot would set the label whenever I approve with a specific message (e.g. "Ready to merge" or "Merge") but I think there are other high prio item to address first.
